version: '3.10'
services:
  app :
    build: ./app/
    depends_on:
      - "postgres_db"
  postgres_db:
    image: "postgres:13"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      
      